server:
  port: 60000

logging:
  #日志配置文件路径
  config: classpath:logback-spring.xml

spring:
  application:
    name: service-auth
  cloud:
    #nacos配置
    nacos:
      discovery:
        #如果是集群搭建，这里配置成Nginx的地址即可或者填写一个集群下多个nacos地址（类似于Eureka集群配置）
        server-addr: ${vm.host}:8848
      config:
        max-retry: 10
  #jackson配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss #日期格式化
    time-zone: GMT+8
    # 序列化相关
    serialization:
      indent_output: true #化输出
    deserialization:
      fail_on_unknown_properties: false #反序列化时对象没有json对应的属性忽略
    defaultPropertyInclusion: NON_EMPTY #如何序列化
    parser:
      allow_unquoted_control_chars: true #允许特殊和转义符
      allow_single_quotes: true #允许单引号
  #datasource配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${vm.host}:3306/service-auth?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root

#MP配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  mapper-locations: classpath*:mappers/*.xml


management:
  endpoints:
    web:
      exposure:
        include: '*'

vm:
  host: www.bird-medical.com