server:
  port: 61000

logging:
  #日志配置文件路径
  config: classpath:logback-spring.xml

#openFeign默认集成了Hystrix
feign:
  hystrix:
    enabled: false
#设置超时时间openFeign默认集成了ribbon
ribbon:
  #服务调用超时时间
  ReadTimeout: 8000
  #服务连接超时时间
  ConnectTimeout: 8000

spring:
  application:
    name: service-log
  cloud:
    #nacos配置
    nacos:
      discovery:
        #如果是集群搭建，这里配置成Nginx的地址即可或者填写一个集群下多个nacos地址（类似于Eureka集群配置）
        server-addr: ${vm.host}:8848
      config:
        max-retry: 10
  #jackson配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss #日期格式化
    time-zone: GMT+8
    # 序列化相关
    serialization:
      indent_output: true #化输出
    deserialization:
      fail_on_unknown_properties: false #反序列化时对象没有json对应的属性忽略
    defaultPropertyInclusion: NON_EMPTY #如何序列化
    parser:
      allow_unquoted_control_chars: true #允许特殊和转义符
      allow_single_quotes: true #允许单引号
  #datasource配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${vm.host}:3306/service-log?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
  #Redis配置
  redis:
    host: ${vm.host}
    port: 6379
    database: 15
  #链路追踪配置
  zipkin:
    base-url: http://${vm.host}:9411
    sender:
      #以http方式想服务提交数据
      type: web
  sleuth:
    sampler:
      #设置采样比例 默认0.1 设置为1
      probability: 1
      #每秒速率
      rate: 300

management:
  endpoints:
    web:
      exposure:
        include: '*'

vm:
  host: www.bird-medical.com